=== Nar-6/Programmation/xml/XML/exo2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="cave">
        <xsd:complexType>            
            <xsd:sequence>

                <xsd:element name="bouteille" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>                            
                            <xsd:element name="marque" type="xsd:string"/>

                            <xsd:element name="composition">
                                <xsd:complexType>
                                    <xsd:sequence>

                                        <xsd:element name="ion" minOccurs="2" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:simpleContent>
                                                    <xsd:extension base="xsd:string">
                                                        <xsd:attribute name="type" type="xsd:string" />
                                                    </xsd:extension>
                                                </xsd:simpleContent>
                                            </xsd:complexType>
                                        </xsd:element>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="source">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="ville" type="xsd:string"/>                                        
                                        <xsd:element name="departement" type="xsd:string"/>                                        
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="code_barre" type="xsd:int"/>

                            <xsd:element name="contenance">
                                <xsd:complexType>
                                    <xsd:simpleContent>
                                        <xsd:extension base="xsd:integer">
                                            <xsd:attribute name="unit" type="xsd:string"/>
                                        </xsd:extension>
                                    </xsd:simpleContent>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="ph">
                                <xsd:complexType>
                                    <xsd:attribute name="valeur" type="xsd:float" />
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>            
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Nar-6/Programmation/xml/XML/exo2.xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<cave xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./exo2.xsd">
    <bouteille>
        <marque>Cristaline</marque>
        <composition>
            <ion type="positif">calcium 71mg/l</ion>
            <ion type="negatif">nitrate 1mg/l</ion>
        </composition>
        <source>
            <ville>Cotonou</ville>
            <departement>Littoral</departement>
        </source>
        <code_barre>3274080005003</code_barre>
        <contenance unit="cl">150</contenance>

        <ph valeur= '7.45' />
    </bouteille>
    <bouteille>
        <marque>Volvic</marque>
        <composition>
            <ion type="positif">calcium 11,5mg/l</ion>
            <ion type="negatif">nitrate 6,3mg/l</ion>
        </composition>
        <source>
            <ville>Parakou</ville>
            <departement>Borgou</departement>
        </source>
        <code_barre>3057640117008</code_barre>
        <contenance unit="cl">50</contenance>
        <ph valeur='7'/>
    </bouteille>
</cave>
